version: '3.7'

services:
  maria_db:
    image: mariadb
    container_name: maria_db
    ports:
      - 3360:3306
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - maria_db:/var/lib/mysql
      - ./dev/wataha.sql:/docker-entrypoint-initdb.d/wataha.sql:ro
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=wataha
      - MYSQL_DATABASE=wataha
      - MYSQL_USER=wataha

  wataha:
    image: chajr/php56-nginx-extended
    container_name: wataha
    volumes:
      - ./dev/log:/var/log/
      - ./conf/wataha-dev.conf:/etc/nginx/conf.d/default.conf
      - ./source:/var/www/html
    ports:
      - 80:8080
    environment:
      - WATAHA_DB_LOGIN=wataha
      - WATAHA_DB_PASS=wataha
      - WATAHA_DB_HOST=maria_db
      - WATAHA_DB_PORT=3306
    depends_on:
      - maria_db

volumes:
  maria_db:
