version: '3.7'

services:
  maria_db:
    image: mariadb
    container_name: maria_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - maria_db:/var/lib/mysql
    env_file:
      - ./etc/.env-db

  wataha:
    image: chajr/wataha
    container_name: wataha
    volumes:
      - ./dev/log:/var/log/
      - wataha-ftp:/var/www/html/FTP
      - wataha-files:/var/www/html/forum/files
      - wataha-upload:/var/www/html/forum/images/avatars/upload
      - wataha-gallery:/var/www/html/forum/images/avatars/gallery
    env_file:
      - ./etc/.env-wataha
    depends_on:
      - maria_db

volumes:
  maria_db:
  wataha-ftp:
  wataha-files:
  wataha-upload:
  wataha-gallery:
