version: '3.7'

services:
  maria_db:
    image: mariadb
    container_name: maria_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - maria_db:/var/lib/mysql
    env_file:
      - ./etc/.env-db

  wataha:
    image: chajr/wataha
    container_name: wataha
    volumes:
      - ./projects/wataha/log:/var/log/
      - wataha-data/FTP:/var/www/html/FTP
      - wataha-data/files:/var/www/html/forum/files
      - wataha-data/images/avatars/upload:/var/www/html/forum/images/avatars/upload
      - wataha-data/images/avatars/gallery:/var/www/html/forum/images/avatars/gallery
    env_file:
      - ./etc/.env-wataha
    depends_on:
      - maria_db

volumes:
  maria_db:
  wataha-data:
